global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ocjdbcmetrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['message:8082']

  - job_name: 'jaeger'
    scrape_interval: 5s
    static_configs:
      - targets: ['jaeger-collector:14268', 'jaeger-agent:5778', 'jaeger-query:16686']

  - job_name: 'nginx'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginx-exporter:9113']
